import {
  BarChart2,
  BedDouble,
  Book,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Car,
  Coffee,
  Dumbbell,
  Droplets,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  Heart,
  HeartHandshake,
  Home,
  Key,
  Laptop,
  MoreHorizontal,
  Navigation,
  Pill,
  Plane,
  PlayCircle,
  Plug,
  PlusCircle,
  ReceiptText,
  Repeat,
  Scissors,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Tag,
  TrendingUp,
  Tv,
  Utensils,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";
import type { LucideProps } from "lucide-react";

export type IconName = string;

export const ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  "bar-chart-2":    BarChart2,
  "bed-double":     BedDouble,
  book:             Book,
  "book-open":      BookOpen,
  briefcase:        Briefcase,
  building:         Building,
  "building-2":     Building2,
  car:              Car,
  coffee:           Coffee,
  droplets:         Droplets,
  dumbbell:         Dumbbell,
  fuel:             Fuel,
  "gamepad-2":      Gamepad2,
  gift:             Gift,
  "graduation-cap": GraduationCap,
  "hand-coins":     HandCoins,
  heart:            Heart,
  "heart-handshake":HeartHandshake,
  home:             Home,
  key:              Key,
  laptop:           Laptop,
  "more-horizontal":MoreHorizontal,
  navigation:       Navigation,
  pill:             Pill,
  plane:            Plane,
  "play-circle":    PlayCircle,
  plug:             Plug,
  "plus-circle":    PlusCircle,
  "receipt-text":   ReceiptText,
  repeat:           Repeat,
  scissors:         Scissors,
  shield:           Shield,
  shirt:            Shirt,
  "shopping-bag":   ShoppingBag,
  "shopping-cart":  ShoppingCart,
  smartphone:       Smartphone,
  sparkles:         Sparkles,
  stethoscope:      Stethoscope,
  tag:              Tag,
  "trending-up":    TrendingUp,
  tv:               Tv,
  utensils:         Utensils,
  wifi:             Wifi,
  wrench:           Wrench,
  zap:              Zap,
};
